apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: argo-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - name: argo-server-container
        image: flowworks-carlsolutions.azurecr.io/flowworks/argo-server:latest
        ports:
        - containerPort: 80    
      imagePullSecrets:
      - name: regsecret